### ISSUE TITLE
Crash with inputs with runs of high number of reads

### ISSUE THREAD

**Issue by kpalin** [wdecoster/nanoget#15]
Runs with >30M reads crash nanoget/NanoPlot with various ways. Crashing with sequencing_summary.txt input (happens with smaller runs) I've worked out by splitting the file into smaller pieces before feeding in. With CRAM input I changed few lines of nanoget to read a single CRAM input at a time (chromosomes still concurrently) which seems to work.

Haven't tested whether something in the environment (Python 3.6.8) causes these issues, With CRAM (at some point) I got error message below. I think it's related to pickling of the large data frames from the different parsing threads.

```
Process Process-1:
Traceback (most recent call last):
  File "/mnt/cgnano/projects/promethion/software/ont_pipe_env/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/mnt/cgnano/projects/promethion/software/ont_pipe_env/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/cgnano/projects/promethion/software/ont_pipe_env/lib/python3.6/concurrent/futures/process.py", line 181, in _process_worker
    result=r))
  File "/mnt/cgnano/projects/promethion/software/ont_pipe_env/lib/python3.6/multiprocessing/queues.py", line 347, in put
    self._writer.send_bytes(obj)
  File "/mnt/cgnano/projects/promethion/software/ont_pipe_env/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/mnt/cgnano/projects/promethion/software/ont_pipe_env/lib/python3.6/multiprocessing/connection.py", line 393, in _send_bytes
    header = struct.pack("!i", n)
struct.error: 'i' format requires -2147483648 <= number <= 2147483647
Traceback (most recent call last):
  File "/mnt/cgnano/projects/promethion/software/ont_pipe_env/bin/NanoPlot", line 10, in <module>
    sys.exit(main())
  File "/mnt/cgnano/projects/promethion/software/ont_pipe_env/lib/python3.6/site-packages/nanoplot/NanoPlot.py", line 60, in main
    barcoded=args.barcoded)
  File "/mnt/cgnano/projects/promethion/software/ont_pipe_env/lib/python3.6/site-packages/nanoget/nanoget.py", line 71, in get_input
    dfs=[out for out in executor.map(extration_function, files)],
  File "/mnt/cgnano/projects/promethion/software/ont_pipe_env/lib/python3.6/site-packages/nanoget/nanoget.py", line 71, in <listcomp>
    dfs=[out for out in executor.map(extration_function, files)],
  File "/mnt/cgnano/projects/promethion/software/ont_pipe_env/lib/python3.6/concurrent/futures/process.py", line 366, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/mnt/cgnano/projects/promethion/software/ont_pipe_env/lib/python3.6/concurrent/futures/_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "/mnt/cgnano/projects/promethion/software/ont_pipe_env/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/mnt/cgnano/projects/promethion/software/ont_pipe_env/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
```

**Comment by wdecoster** [comment]
Oh but 30M is an enormous amount of reads, we never have that many reads. So I can't compare with what I test. Using multiple promethion runs means it is done in parallel, same as your observation that breaking up the summaries can solve it.
This issue could probably be fixed by using dask rather than pandas. Perhaps that wouldn't be too hard. I don't have much time left these days, unfortunately. I'll do my best, but you are of course most welcome to give this a try.

**Comment by kpalin** [comment]
We'd definitely prefer to have much fewer (and longer) reads but in future and in counting applications 30M is not that many. 

I appreciate your time constraints. Building and maintaining community standard software is not light work.

I have bad experiences with dask but maybe it could be worked out. I'm worried the 'data for each read in a dataframe' approach doesn't scale too well for big runs but working with summary statistics would be a major architectural change for NanoPlot. That being said, my current solution to this is to let the analysis pipeline ignore crashing NanoPlot.

**Comment by wdecoster** [comment]
Well, about my experiences with dask I just know it does exist. It seems interesting, so I want to look into it. I just won't make any promises.

**Comment by wdecoster** [comment]
Thank you for your patience. NanoPlot v1.27.0, available on pypi/pip has a `--huge` argument which could solve your issue, as it allows only a single input file and does not use concurrent.futures and therefore the limitations of pickling.
