### ISSUE TITLE
Mixed timestamp offset issues

### ISSUE THREAD

**Issue by jchorl** [wdecoster/nanoget#32]
I see nanoget is trying to normalize timezones here: https://github.com/wdecoster/nanoget/blob/1cd145c5aadca236f700591177d6762a5733c34e/nanoget/nanoget.py#L153

This breaks when you have timestamps of different offsets:
```
>>> time_zero = datetime.datetime.fromisoformat("2023-09-12 22:36:47+00:00")
>>> first = datetime.datetime.fromisoformat("2023-09-12 22:36:47+00:00")
>>> second = datetime.datetime.fromisoformat("2023-09-13 14:17:12.357928+02:00")
>>> 
>>> series = pd.Series([first, second])
>>> series.dt.tz_convert('UTC').dt.tz_localize(None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/pandas/core/generic.py", line 6202, in __getattr__
    return object.__getattribute__(self, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pandas/core/accessor.py", line 224, in __get__
    accessor_obj = self._accessor(obj)
                   ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pandas/core/indexes/accessors.py", line 608, in __new__
    raise AttributeError("Can only use .dt accessor with datetimelike values")
AttributeError: Can only use .dt accessor with datetimelike values. Did you mean: 'at'?
```

You can normalize them:
```
>>> series.apply(lambda x: x.astimezone(timezone('UTC')))
0          2023-09-12 22:36:47+00:00
1   2023-09-13 12:17:12.357928+00:00
dtype: datetime64[ns, UTC]
```

While odd to process timestamps with different offsets, I feel like this should work.

Thoughts on updating that function?

As a tangential question - how critical is timestamp parsing to nanoget functionality? Feels like a can of worms that would be nice to avoid in general.

**Comment by wdecoster** [comment]
Hi,

Oh well, time zones are terrible right? Timestamp parsing is there to produce plots like cumulative yield or active pores per time interval. Fastq files from ONT basecallers typically have time stamps, and also the sequencing_summary file has that information. So I would like to keep it. 
It used to be a time zone agnostic time stamp, which did not cause any troubles, and the code you pointed to above was only introduced to deal with timezones. But it seems incorrectly now, so your suggestion is highly appreciated. Were you planning to open a PR for this?

Best,
Wouter

**Comment by jchorl** [comment]
https://github.com/wdecoster/nanoget/pull/33

**Comment by wdecoster** [comment]
Thank you!
